# Generated by Django 4.0.3 on 2022-03-08 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the address for better usability')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(max_length=100, verbose_name='ZIP/Postal code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address_1', models.CharField(max_length=100, verbose_name='Address')),
                ('address_2', models.CharField(max_length=100, verbose_name='Apartment, suite, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name'), ('country', 'state', 'postal_code', 'city', 'address_1', 'address_2', 'user')},
            },
        ),
    ]
